"""Subclass of MyFrame1, which is generated by wxFormBuilder."""

import wx
import CCT_report

# Implementing MyFrame1
class MyFrame( CCT_report.MyFrame1 ):
	def __init__( self, parent ):
		CCT_report.MyFrame1.__init__( self, parent )
	
