"""Subclass of MyFrame1, which is generated by wxFormBuilder."""
# -*- coding: utf-8 -*-

import wx
import wx.xrc
import sys
import datetime as dt
from redmine import Redmine
from datetime import *
import CCT_report

default_encoding = 'utf-8'
if sys.getdefaultencoding() != default_encoding:
    reload(sys)
    sys.setdefaultencoding(default_encoding)    

# Implementing MyFrame1
class MyFrame( CCT_report.MyFrame1 ):
  def __init__( self, parent ):
    CCT_report.MyFrame1.__init__( self, parent )
   
#def close button to Close    
  def closebutton(self, event):
    self.Close(True)
    
#def close button destroy windows    
  def closewindow(self, event):
    self.Destroy()

#def getbutton
  def getbutton(self, event):
    self.m_statusBar.SetStatusText( 'Please wait a minute...' )

#   ----clear report fields----    
    self.omnicast_textCtrl.Clear()
    self.security_textCtrl.Clear()
    self.milestone_textCtrl.Clear()
    self.nd8321_textCtrl.Clear()
    self.nd8322p_textCtrl.Clear()
    self.onvif_textCtrl.Clear()
    self.shpherd_textCtrl.Clear()
    self.vast_textCtrl.Clear()
    
    tester_account = self.account_textCtrl.GetValue()
    tester_password = self.password_textCtrl.GetValue()
    model_name = self.model_textCtrl.GetValue()
    brand_name = self.brand_textCtrl.GetValue()
    version_name = self.version_textCtrl.GetValue()
    testrail = self.testrail_textCtrl.GetValue()
    project_id = self.project_textCtrl.GetValue()
    common_project_id = self.common_textCtrl.GetValue()
    test_type = self.type_checkList.GetCheckedStrings()
    
    sys_today = dt.date.today()
    tester_today = sys_today.isoformat()
    
    redmine = Redmine("http://dqa02/redmine/", username=tester_account, password=tester_password)
    project = redmine.project.get(project_id)
    if self.common_textCtrl.IsModified() is True:
        common_project = redmine.project.get(common_project_id)
    redmine_user = redmine.user.filter(name=tester_account)
    
    omnicast_issue = []
    security_issue = []
    milestone_issue = []
    nd8321_issue = []
    nd8322p_issue = []
    onvif_issue =[]
    shpherd_issue =[]
    vast_issue=[]
    
    omnicast_suggestion = []
    security_suggestion = []
    milestone_suggestion = []
    nd8321_suggestion = []
    nd8322p_suggestion = []
    onvif_suggestion =[]
    shpherd_suggestion =[]
    vast_suggestion=[]
    
    omnicast_reopen = []
    security_reopen = []
    milestone_reopen = []
    nd8321_reopen = []
    nd8322p_reopen = []
    onvif_reopen =[]
    shpherd_reopen =[]
    vast_reopen=[]
    
    for issue in project.issues:
        if str(issue.tracker) == "Compatibility Bug":
            if issue.author.id == redmine_user[0].id:
                bugid = str(issue.id)
                priority = str(issue.priority)
                severity = str(issue.custom_fields[0].value)
                issuetitle = str(issue)
                testtype = str(issue.custom_fields[3].value)
                if testtype == "Genetec-Omnicast" and str(issue.status)=="REOPENED":
                    omnicast_reopen.append("#"+bugid+" [" +priority+ "]""[" +severity+ "]""[" +testtype+ "]" +issuetitle+"\n")
                if testtype == "Genetec-Security center" and str(issue.status)=="REOPENED":
                    security_reopen.append("#"+bugid+" [" +priority+ "]""[" +severity+ "]""[" +testtype+ "]" +issuetitle+"\n")
                if testtype == "Milestone" and str(issue.status)=="REOPENED" or testtype == "Enterprise" and str(issue.status)=="REOPENED" or testtype == "Corporate" and str(issue.status)=="REOPENED":
                    milestone_reopen.append("#"+bugid+" [" +priority+ "]""[" +severity+ "]""[" +testtype+ "]" +issuetitle+"\n")
                if testtype == "ND8321" and str(issue.status)=="REOPENED":
                    nd8321_reopen.append("#"+bugid+" [" +priority+ "]""[" +severity+ "]""[" +testtype+ "]" +issuetitle+"\n")
                if testtype == "ND8322P" and str(issue.status)=="REOPENED":
                    nd8322p_reopen.append("#"+bugid+" [" +priority+ "]""[" +severity+ "]""[" +testtype+ "]" +issuetitle+"\n")
                if testtype == "ONVIF" and str(issue.status)=="REOPENED":
                    onvif_reopen.append("#"+bugid+" [" +priority+ "]""[" +severity+ "]""[" +testtype+ "]" +issuetitle+"\n")
                if testtype == "Shepherd" and str(issue.status)=="REOPENED":
                    shpherd_reopen.append("#"+bugid+" [" +priority+ "]""[" +severity+ "]""[" +testtype+ "]" +issuetitle+"\n")
                if testtype == "VAST" and str(issue.status)=="REOPENED":
                    vast_reopen.append("#"+bugid+" [" +priority+ "]""[" +severity+ "]""[" +testtype+ "]" +issuetitle+"\n")
                    
                if str(issue.custom_fields[4].value) == str(version_name): 
                    if testtype == "Genetec-Omnicast" and not str(issue.status) =="REOPENED" and not severity =="Suggestion":
                        omnicast_issue.append("#"+bugid+" [" +priority+ "]""[" +severity+ "]""[" +testtype+ "]" +issuetitle+"\n")
                    if testtype == "Genetec-Omnicast" and severity == "Suggestion":
                        omnicast_suggestion.append("#"+bugid+" [" +priority+ "]""[" +severity+ "]""[" +testtype+ "]" +issuetitle+"\n")
                           
                    if testtype == "Genetec-Security center" and not str(issue.status) =="REOPENED" and not severity =="Suggestion":  
                        security_issue.append("#"+bugid+" [" +priority+ "]""[" +severity+ "]""[" +testtype+ "]" +issuetitle+"\n")
                    if testtype == "Genetec-Security center" and severity == "Suggestion":
                        security_suggestion.append("#"+bugid+" [" +priority+ "]""[" +severity+ "]""[" +testtype+ "]" +issuetitle+"\n")                                            
                        
                    if testtype == "Milestone" and not str(issue.status) =="REOPENED" and not severity == "Suggestion":   
                        milestone_issue.append("#"+bugid+" [" +priority+ "]""[" +severity+ "]""[" +testtype+ "]" +issuetitle+"\n")
                    if testtype == "Enterprise" and not str(issue.status) =="REOPENED" and not severity == "Suggestion":   
                        milestone_issue.append("#"+bugid+" [" +priority+ "]""[" +severity+ "]""[" +testtype+ "]" +issuetitle+"\n")        
                    if testtype == "Corporate" and not str(issue.status) =="REOPENED" and not severity == "Suggestion":   
                        milestone_issue.append("#"+bugid+" [" +priority+ "]""[" +severity+ "]""[" +testtype+ "]" +issuetitle+"\n")
                    if testtype == "Milestone" and severity == "Suggestion" or testtype == "Enterprise" and severity == "Suggestion" or testtype == "Corporate" and severity == "Suggestion":
                        milestone_suggestion.append("#"+bugid+" [" +priority+ "]""[" +severity+ "]""[" +testtype+ "]" +issuetitle+"\n")
                                                                                
                    if testtype == "ND8321" and not str(issue.status) =="REOPENED" and not severity =="Suggestion":  
                        nd8321_issue.append("#"+bugid+" [" +priority+ "]""[" +severity+ "]""[" +testtype+ "]" +issuetitle+"\n")
                    if testtype == "ND8321" and severity == "Suggestion":
                        nd8321_suggestion.append("#"+bugid+" [" +priority+ "]""[" +severity+ "]""[" +testtype+ "]" +issuetitle+"\n")                                               
                        
                    if testtype == "ND8322P" and not str(issue.status) =="REOPENED" and not severity =="Suggestion":   
                        nd8322p_issue.append("#"+bugid+" [" +priority+ "]""[" +severity+ "]""[" +testtype+ "]" +issuetitle+"\n")
                    if testtype == "ND8322P" and severity == "Suggestion":
                        nd8322p_suggestion.append("#"+bugid+" [" +priority+ "]""[" +severity+ "]""[" +testtype+ "]" +issuetitle+"\n")                                             
                        
                    if testtype == "ONVIF" and not str(issue.status) =="REOPENED" and not severity =="Suggestion":   
                        onvif_issue.append("#"+bugid+" [" +priority+ "]""[" +severity+ "]""[" +testtype+ "]" +issuetitle+"\n") 
                    if testtype == "ONVIF" and severity == "Suggestion":
                        onvif_suggestion.append("#"+bugid+" [" +priority+ "]""[" +severity+ "]""[" +testtype+ "]" +issuetitle+"\n")
                                                                         
                    if testtype == "Shepherd" and not str(issue.status) =="REOPENED" and not severity =="Suggestion":   
                        shpherd_issue.append("#"+bugid+" [" +priority+ "]""[" +severity+ "]""[" +testtype+ "]" +issuetitle+"\n")
                    if testtype == "Shepherd" and severity == "Suggestion":
                        shpherd_suggestion.append("#"+bugid+" [" +priority+ "]""[" +severity+ "]""[" +testtype+ "]" +issuetitle+"\n")                         
                                                
                    if testtype == "VAST" and not str(issue.status) =="REOPENED" and not severity =="Suggestion":   
                        vast_issue.append("#"+bugid+" [" +priority+ "]""[" +severity+ "]""[" +testtype+ "]" +issuetitle+"\n") 
                    if testtype == "VAST" and severity == "Suggestion":
                        vast_suggestion.append("#"+bugid+" [" +priority+ "]""[" +severity+ "]""[" +testtype+ "]" +issuetitle+"\n")                                                                       
                                         
    omnicast_buglist = ''
    security_buglist = ''
    milestone_buglist = ''
    nd8321_buglist = ''
    nd8322p_buglist = ''
    onvif_buglist =''
    shpherd_buglist =''
    vast_buglist =''
    
    for bug in omnicast_issue:
        omnicast_buglist+=bug
        
    for bug in security_issue:
        security_buglist+=bug
        
    for bug in milestone_issue:
        milestone_buglist+=bug
        
    for bug in nd8321_issue:
        nd8321_buglist+=bug
        
    for bug in nd8322p_issue:
        nd8322p_buglist+=bug
        
    for bug in onvif_issue:
        onvif_buglist+=bug
        
    for bug in shpherd_issue:
        shpherd_buglist+=bug

    for bug in vast_issue:
        vast_buglist+=bug


    omnicast_suggestionlist = ''
    security_suggestionlist = ''
    milestone_suggestionlist = ''
    nd8321_suggestionlist = ''
    nd8322p_suggestionlist = ''
    onvif_suggestionlist =''
    shpherd_suggestionlist =''
    vast_suggestionlist=''   
    
    for suggestion in omnicast_suggestion:
        omnicast_suggestionlist+=suggestion
        
    for suggestion in security_suggestion:
        security_suggestionlist+=suggestion
        
    for suggestion in milestone_suggestion:
        milestone_suggestionlist+=suggestion
        
    for suggestion in nd8321_suggestion:
        nd8321_suggestionlist+=suggestion
        
    for suggestion in nd8322p_suggestion:
        nd8322p_suggestionlist+=suggestion
        
    for suggestion in onvif_suggestion:
        onvif_suggestionlist+=suggestion
        
    for suggestion in shpherd_suggestion:
        shpherd_suggestionlist+=suggestion

    for suggestion in vast_suggestion:
        vast_suggestionlist+=suggestion
    
      
    omnicast_reopenlist = ''
    security_reopenlist = ''
    milestone_reopenlist = ''
    nd8321_reopenlist = ''
    nd8322p_reopenlist = ''
    onvif_reopenlist =''
    shpherd_reopenlist =''
    vast_reopenlist=''  
      
    for reopen in omnicast_reopen:
        omnicast_reopenlist+=reopen
        
    for reopen in security_reopen:
        security_reopenlist+=reopen
        
    for reopen in milestone_reopen:
        milestone_reopenlist+=reopen
        
    for reopen in nd8321_reopen:
        nd8321_reopenlist+=reopen
        
    for reopen in nd8322p_reopen:
        nd8322p_reopenlist+=reopen
        
    for reopen in onvif_reopen:
        onvif_reopenlist+=reopen
        
    for reopen in shpherd_reopen:
        shpherd_reopenlist+=reopen

    for reopen in vast_reopen:
        vast_reopenlist+=reopen   
         
#   --------------------------------------------------------Common project issues------------------------------------------------------------------------------------
    common_omnicast_issue = []
    common_security_issue = []
    common_milestone_issue = []
    common_nd8321_issue = []
    common_nd8322p_issue = []
    common_onvif_issue =[]
    common_shpherd_issue =[]
    common_vast_issue=[]
    
    common_omnicast_suggestion = []
    common_security_suggestion = []
    common_milestone_suggestion = []
    common_nd8321_suggestion = []
    common_nd8322p_suggestion = []
    common_onvif_suggestion =[]
    common_shpherd_suggestion =[]
    common_vast_suggestion=[]
    
    common_omnicast_reopen = []
    common_security_reopen = []
    common_milestone_reopen = []
    common_nd8321_reopen = []
    common_nd8322p_reopen = []
    common_onvif_reopen =[]
    common_shpherd_reopen =[]
    common_vast_reopen=[]
    
    if self.common_textCtrl.IsModified() is True:
        for issue in common_project.issues:
            if str(issue.tracker) == "Compatibility Bug":
                if issue.author.id == redmine_user[0].id:
                    common_bugid = str(issue.id)
                    common_priority = str(issue.priority)
                    common_severity = str(issue.custom_fields[0].value)
                    common_issuetitle = str(issue)
                    common_testtype = str(issue.custom_fields[3].value)
                    if common_testtype == "Genetec-Omnicast" and str(issue.status)=="REOPENED":
                        common_omnicast_reopen.append("#"+common_bugid+" [" +common_priority+ "]""[" +common_severity+ "]""[" +common_testtype+ "]" +common_issuetitle+"\n")
                    if common_testtype == "Genetec-Security center" and str(issue.status)=="REOPENED":
                        common_security_reopen.append("#"+common_bugid+" [" +common_priority+ "]""[" +common_severity+ "]""[" +common_testtype+ "]" +common_issuetitle+"\n")                   
                    if common_testtype == "Milestone" and str(issue.status)=="REOPENED":
                        common_milestone_reopen.append("#"+common_bugid+" [" +common_priority+ "]""[" +common_severity+ "]""[" +common_testtype+ "]" +common_issuetitle+"\n")                   
                    if common_testtype == "Enterprise" and str(issue.status)=="REOPENED":
                        common_milestone_reopen.append("#"+common_bugid+" [" +common_priority+ "]""[" +common_severity+ "]""[" +common_testtype+ "]" +common_issuetitle+"\n") 
                    if common_testtype == "Corporate" and str(issue.status)=="REOPENED":
                        common_milestone_reopen.append("#"+common_bugid+" [" +common_priority+ "]""[" +common_severity+ "]""[" +common_testtype+ "]" +common_issuetitle+"\n") 
                    if common_testtype == "ND8321" and str(issue.status)=="REOPENED":
                        common_nd8321_reopen.append("#"+common_bugid+" [" +common_priority+ "]""[" +common_severity+ "]""[" +common_testtype+ "]" +common_issuetitle+"\n")                  
                    if common_testtype == "ND8322P" and str(issue.status)=="REOPENED":
                        common_nd8322p_reopen.append("#"+common_bugid+" [" +common_priority+ "]""[" +common_severity+ "]""[" +common_testtype+ "]" +common_issuetitle+"\n")
                    if common_testtype == "ONVIF" and str(issue.status)=="REOPENED":
                        common_onvif_reopen.append("#"+common_bugid+" [" +common_priority+ "]""[" +common_severity+ "]""[" +common_testtype+ "]" +common_issuetitle+"\n")
                    if common_testtype == "Shepherd" and str(issue.status)=="REOPENED":
                        common_shpherd_reopen.append("#"+common_bugid+" [" +common_priority+ "]""[" +common_severity+ "]""[" +common_testtype+ "]" +common_issuetitle+"\n")
                    if common_testtype == "VAST" and str(issue.status)=="REOPENED":
                        common_vast_reopen.append("#"+common_bugid+" [" +common_priority+ "]""[" +common_severity+ "]""[" +common_testtype+ "]" +issuetitle+"\n")
                    
                    if str(issue.custom_fields[4].value) == str(version_name):
                        if common_testtype == "Genetec-Omnicast" and not str(issue.status) =="REOPENED" and not common_severity =="Suggestion":
                            common_omnicast_issue.append("#"+common_bugid+" [" +common_priority+ "]""[" +common_severity+ "]""[" +common_testtype+ "]" +common_issuetitle+"\n")
                        if common_testtype == "Genetec-Omnicast" and common_severity == "Suggestion":
                            common_omnicast_suggestion.append("#"+common_bugid+" [" +common_priority+ "]""[" +common_severity+ "]""[" +common_testtype+ "]" +common_issuetitle+"\n")


                        if common_testtype == "Genetec-Security center" and not str(issue.status) =="REOPENED" and not common_severity =="Suggestion":  
                            common_security_issue.append("#"+common_bugid+" [" +common_priority+ "]""[" +common_severity+ "]""[" +common_testtype+ "]" +common_issuetitle+"\n")
                        if common_testtype == "Genetec-Security center" and common_severity == "Suggestion":
                            common_security_suggestion.append("#"+common_bugid+" [" +common_priority+ "]""[" +common_severity+ "]""[" +common_testtype+ "]" +common_issuetitle+"\n")                      
                        
                        if common_testtype == "Milestone" and not str(issue.status) =="REOPENED" and not common_severity == "Suggestion":   
                            common_milestone_issue.append("#"+common_bugid+" [" +common_priority+ "]""[" +common_severity+ "]""[" +common_testtype+ "]" +common_issuetitle+"\n")
                        if common_testtype == "Enterprise" and not str(issue.status) =="REOPENED" and not common_severity == "Suggestion":   
                            common_milestone_issue.append("#"+common_bugid+" [" +common_priority+ "]""[" +common_severity+ "]""[" +common_testtype+ "]" +common_issuetitle+"\n")                            
                        if common_testtype == "Corporate" and not str(issue.status) =="REOPENED" and not common_severity == "Suggestion":   
                            common_milestone_issue.append("#"+common_bugid+" [" +common_priority+ "]""[" +common_severity+ "]""[" +common_testtype+ "]" +common_issuetitle+"\n")
                                                        
                        if common_testtype == "Milestone" and common_severity == "Suggestion" or common_testtype == "Enterprise" and common_severity == "Suggestion" or common_testtype == "Corporate" and common_severity == "Suggestion":
                            common_milestone_suggestion.append("#"+common_bugid+" [" +common_priority+ "]""[" +common_severity+ "]""[" +common_testtype+ "]" +common_issuetitle+"\n")                               
                        
                        if common_testtype == "ND8321" and not str(issue.status) =="REOPENED" and not common_severity =="Suggestion":  
                            common_nd8321_issue.append("#"+common_bugid+" [" +common_priority+ "]""[" +common_severity+ "]""[" +common_testtype+ "]" +common_issuetitle+"\n")
                        if common_testtype == "ND8321" and common_severity == "Suggestion":
                            common_nd8321_suggestion.append("#"+common_bugid+" [" +common_priority+ "]""[" +common_severity+ "]""[" +common_testtype+ "]" +common_issuetitle+"\n")
                                                                   
                        if common_testtype == "ND8322P" and not str(issue.status) =="REOPENED" and not common_severity =="Suggestion":   
                            common_nd8322p_issue.append("#"+common_bugid+" [" +common_priority+ "]""[" +common_severity+ "]""[" +common_testtype+ "]" +common_issuetitle+"\n")
                        if common_testtype == "ND8322P" and common_severity == "Suggestion":
                            common_nd8322p_suggestion.append("#"+common_bugid+" [" +common_priority+ "]""[" +common_severity+ "]""[" +common_testtype+ "]" +common_issuetitle+"\n")
                        
                        if common_testtype == "ONVIF" and not str(issue.status) =="REOPENED" and not common_severity =="Suggestion":   
                            common_onvif_issue.append("#"+common_bugid+" [" +common_priority+ "]""[" +common_severity+ "]""[" +common_testtype+ "]" +common_issuetitle+"\n") 
                        if common_testtype == "ONVIF" and common_severity == "Suggestion":
                            common_onvif_suggestion.append("#"+common_bugid+" [" +common_priority+ "]""[" +common_severity+ "]""[" +common_testtype+ "]" +common_issuetitle+"\n")                    
                                                 
                        if common_testtype == "Shepherd" and not str(issue.status) =="REOPENED" and not common_severity =="Suggestion":   
                            common_shpherd_issue.append("#"+common_bugid+" [" +common_priority+ "]""[" +common_severity+ "]""[" +common_testtype+ "]" +common_issuetitle+"\n")
                        if common_testtype == "Shepherd" and common_severity == "Suggestion":
                            common_shpherd_suggestion.append("#"+common_bugid+" [" +common_priority+ "]""[" +common_severity+ "]""[" +common_testtype+ "]" +common_issuetitle+"\n")
                                                                       
                        if common_testtype == "VAST" and not str(issue.status) =="REOPENED" and not common_severity =="Suggestion":   
                            common_vast_issue.append("#"+common_bugid+" [" +common_priority+ "]""[" +common_severity+ "]""[" +common_testtype+ "]" +common_issuetitle+"\n") 
                        if common_testtype == "VAST" and common_severity == "Suggestion":
                            common_vast_suggestion.append("#"+common_bugid+" [" +common_priority+ "]""[" +common_severity+ "]""[" +common_testtype+ "]" +common_issuetitle+"\n")    
                                                                   
                                         
    common_omnicast_buglist = ''
    common_security_buglist = ''
    common_milestone_buglist = ''
    common_nd8321_buglist = ''
    common_nd8322p_buglist = ''
    common_onvif_buglist =''
    common_shpherd_buglist =''
    common_vast_buglist =''
    
    for bug in common_omnicast_issue:
        common_omnicast_buglist+=bug
        
    for bug in common_security_issue:
        common_security_buglist+=bug
        
    for bug in common_milestone_issue:
        common_milestone_buglist+=bug
        
    for bug in common_nd8321_issue:
        common_nd8321_buglist+=bug
        
    for bug in common_nd8322p_issue:
        common_nd8322p_buglist+=bug
        
    for bug in common_onvif_issue:
        common_onvif_buglist+=bug
        
    for bug in common_shpherd_issue:
        common_shpherd_buglist+=bug

    for bug in common_vast_issue:
        common_vast_buglist+=bug


    common_omnicast_suggestionlist = ''
    common_security_suggestionlist = ''
    common_milestone_suggestionlist = ''
    common_nd8321_suggestionlist = ''
    common_nd8322p_suggestionlist = ''
    common_onvif_suggestionlist =''
    common_shpherd_suggestionlist =''
    common_vast_suggestionlist=''   
    
    for suggestion in common_omnicast_suggestion:
        common_omnicast_suggestionlist+=suggestion
        
    for suggestion in common_security_suggestion:
        common_security_suggestionlist+=suggestion
        
    for suggestion in common_milestone_suggestion:
        common_milestone_suggestionlist+=suggestion
        
    for suggestion in common_nd8321_suggestion:
        common_nd8321_suggestionlist+=suggestion
        
    for suggestion in common_nd8322p_suggestion:
        common_nd8322p_suggestionlist+=suggestion
        
    for suggestion in common_onvif_suggestion:
        common_onvif_suggestionlist+=suggestion
        
    for suggestion in common_shpherd_suggestion:
        common_shpherd_suggestionlist+=suggestion

    for suggestion in common_vast_suggestion:
        common_vast_suggestionlist+=suggestion
    
      
    common_omnicast_reopenlist = ''
    common_security_reopenlist = ''
    common_milestone_reopenlist = ''
    common_nd8321_reopenlist = ''
    common_nd8322p_reopenlist = ''
    common_onvif_reopenlist =''
    common_shpherd_reopenlist =''
    common_vast_reopenlist=''  
      
    for reopen in common_omnicast_reopen:
        common_omnicast_reopenlist+=reopen
        
    for reopen in common_security_reopen:
        common_security_reopenlist+=reopen
        
    for reopen in common_milestone_reopen:
        common_milestone_reopenlist+=reopen
        
    for reopen in common_nd8321_reopen:
        common_nd8321_reopenlist+=reopen
        
    for reopen in common_nd8322p_reopen:
        common_nd8322p_reopenlist+=reopen
        
    for reopen in common_onvif_reopen:
        common_onvif_reopenlist+=reopen
        
    for reopen in common_shpherd_reopen:
        common_shpherd_reopenlist+=reopen

    for reopen in common_vast_reopen:
        common_vast_reopenlist+=reopen
    
    common_project_modify = self.common_textCtrl.IsModified()
    if common_project_modify is False:
        common_project_link="N\A\n\n"
        common_omnicast_buglist="N\A\n"
        common_security_buglist="N\A\n"
        common_milestone_buglist="N\A\n"
        common_nd8321_buglist="N\A\n"
        common_nd8322p_buglist="N\A\n"
        common_onvif_buglist="N\A\n"
        common_shpherd_buglist="N\A\n"
        common_vast_buglist="N\A\n"
    else:
        common_project_link="http://dqa02/projects/"+common_project_id+"/issues?set_filter=1&tracker_id=69\n\n"
        
    testrail_modify = self.testrail_textCtrl.IsModified()
    if testrail_modify is False:
        testrail_link="N\A"
    else:
        testrail_link=testrail    
#   --------------------------------------------------------Report format------------------------------------------------------------------------------------
#   ----omnicast_report----
    omnicast_report=\
    "[Final Report] "+ model_name.upper()+"-"+brand_name.upper()+"-"+ version_name + " Genetec-Omnicast test --- test on " + tester_today+"\n\n"\
    "Dear David,\n"\
    "The bug status of "+ model_name.upper()+"-"+brand_name.upper()+"-"+ version_name +" Genetec-Omnicast test, "+str(len(omnicast_issue)+len(common_omnicast_issue))+" bugs are opened and "+ str(len(omnicast_suggestion)+len(common_omnicast_suggestion)) +" suggestions are listed.\n"\
    "Please check it. Thanks for your great help!!\n\n"\
    "PS:\n"\
    "Full Test\n\n"\
    "TestRail link:\n"\
    +testrail_link+"\n\n"\
    "The file location:\n"\
    "\\\dqa03\QMD\設計驗證部\\06_驗證六組\\03_Genetec\\99_Genetec_Omnicast_Report_On_going"+"\\" +model_name.upper()+"-"+brand_name.upper()+"\\"+version_name+"\n\n"\
    "The Project common bug link:\n"\
    +common_project_link\
    +"The Project common bug list:\n"\
    +common_omnicast_buglist+"\n"\
    +model_name.upper()+" bug link:\n"\
    +"http://dqa02/projects/"+project_id+"/issues?set_filter=1&tracker_id=69\n\n"\
    +model_name.upper()+" bug list:\n"\
    +omnicast_buglist+"\n"\
    +"Reopen bug:\n"\
    +common_omnicast_reopenlist\
    +omnicast_reopenlist+"\n"\
    +"Suggestion:\n"\
    +common_omnicast_suggestionlist\
    +omnicast_suggestionlist+"\n"\
    +"Best Regards,\n"\
    +tester_account.capitalize()

#   ----security_report---
    security_report=\
    "[Final Report] "+ model_name.upper()+"-"+brand_name.upper()+"-"+ version_name + " Genetec-Security Center test --- test on " + tester_today+"\n\n"\
    "Dear David,\n"\
    "The bug status of "+ model_name.upper()+"-"+brand_name.upper()+"-"+ version_name +" Genetec-Security Center test, "+str(len(security_issue)+len(common_security_issue))+" bugs are opened and "+ str(len(security_suggestion)+len(common_security_suggestion)) +" suggestions are listed.\n"\
    "Please check it. Thanks for your great help!!\n\n"\
    "PS:\n"\
    "Full Test\n\n"\
    "TestRail link:\n"\
    +testrail_link+"\n\n"\
    "The file location:\n"\
    "\\\dqa03\QMD\設計驗證部\\06_驗證六組\\03_Genetec\\98_Genetec_Security_Center_Report_On_going"+"\\" +model_name.upper()+"-"+brand_name.upper()+"\\"+version_name+"\n\n"\
    "The Project common bug link:\n"\
    +common_project_link\
    +"The Project common bug list:\n"\
    +common_security_buglist+"\n"\
    +model_name.upper()+" bug link:\n"\
    +"http://dqa02/projects/"+project_id+"/issues?set_filter=1&tracker_id=69\n\n"\
    +model_name.upper()+" bug list:\n"\
    +security_buglist+"\n"\
    +"Reopen bug:\n"\
    +common_security_reopenlist\
    +security_reopenlist+"\n"\
    +"Suggestion:\n"\
    +common_security_suggestionlist\
    +security_suggestionlist+"\n"\
    +"Best Regards,\n"\
    +tester_account.capitalize()

#   ----milestone_report---        
    milestone_report=\
    "[Final Report] "+ model_name.upper()+"-"+brand_name.upper()+"-"+ version_name + " Milestone test --- test on " + tester_today+"\n\n"\
    "Dear David,\n"\
    "The bug status of "+ model_name.upper()+"-"+brand_name.upper()+"-"+ version_name +" Milestone test, "+str(len(milestone_issue)+len(common_milestone_issue))+" bugs are opened and "+ str(len(milestone_suggestion)+len(common_milestone_suggestion)) +" suggestions are listed.\n"\
    "Please check it. Thanks for your great help!!\n\n"\
    "PS:\n"\
    "Full Test\n\n"\
    "TestRail link:\n"\
    +testrail_link+"\n\n"\
    "The file location:\n"\
    "N/A\n\n"\
    "The Project common bug link:\n"\
    +common_project_link\
    +"The Project common bug list:\n"\
    +common_milestone_buglist+"\n"\
    +model_name.upper()+" bug link:\n"\
    +"http://dqa02/projects/"+project_id+"/issues?set_filter=1&tracker_id=69\n\n"\
    +model_name.upper()+" bug list:\n"\
    +milestone_buglist+"\n"\
    +"Reopen bug:\n"\
    +common_milestone_reopenlist\
    +milestone_reopenlist+"\n"\
    +"Suggestion:\n"\
    +common_milestone_suggestionlist\
    +milestone_suggestionlist+"\n"\
    +"Best Regards,\n"\
    +tester_account.capitalize()

#   ----nd8321_report---         
    nd8321_report=\
    "[Final Report] "+ model_name.upper()+"-"+brand_name.upper()+"-"+ version_name + " ND8321 test --- test on " + tester_today+"\n\n"\
    "Dear David,\n"\
    "The bug status of "+ model_name.upper()+"-"+brand_name.upper()+"-"+ version_name +" ND8321 test, "+str(len(nd8321_issue)+len(common_nd8321_issue))+" bugs are opened and "+ str(len(nd8321_suggestion)+len(common_nd8321_suggestion)) +" suggestions are listed.\n"\
    "Please check it. Thanks for your great help!!\n\n"\
    "PS:\n"\
    "Full Test\n\n"\
    "TestRail link:\n"\
    +testrail_link+"\n\n"\
    "The file location:\n"\
    "N/A\n\n"\
    "The Project common bug link:\n"\
    +common_project_link\
    +"The Project common bug list:\n"\
    +common_nd8321_buglist+"\n"\
    +model_name.upper()+" bug link:\n"\
    +"http://dqa02/projects/"+project_id+"/issues?set_filter=1&tracker_id=69\n\n"\
    +model_name.upper()+" bug list:\n"\
    +nd8321_buglist+"\n"\
    +"Reopen bug:\n"\
    +common_nd8321_reopenlist\
    +nd8321_reopenlist+"\n"\
    +"Suggestion:\n"\
    +common_nd8321_suggestionlist\
    +nd8321_suggestionlist+"\n"\
    +"Best Regards,\n"\
    +tester_account.capitalize()

#   ----nd8322p_report---         
    nd8322p_report=\
    "[Final Report] "+ model_name.upper()+"-"+brand_name.upper()+"-"+ version_name + " ND8322P test --- test on " + tester_today+"\n\n"\
    "Dear David,\n"\
    "The bug status of "+ model_name.upper()+"-"+brand_name.upper()+"-"+ version_name +" ND8322P test, "+str(len(nd8322p_issue)+len(common_nd8322p_issue))+" bugs are opened and "+ str(len(nd8322p_suggestion)+len(common_nd8322p_suggestion)) +" suggestions are listed.\n"\
    "Please check it. Thanks for your great help!!\n\n"\
    "PS:\n"\
    "Full Test\n\n"\
    "TestRail link:\n"\
    +testrail_link+"\n\n"\
    "The file location:\n"\
    "N/A\n\n"\
    "The Project common bug link:\n"\
    +common_project_link\
    +"The Project common bug list:\n"\
    +common_nd8322p_buglist+"\n"\
    +model_name.upper()+" bug link:\n"\
    +"http://dqa02/projects/"+project_id+"/issues?set_filter=1&tracker_id=69\n\n"\
    +model_name.upper()+" bug list:\n"\
    +nd8322p_buglist+"\n"\
    +"Reopen bug:\n"\
    +common_nd8322p_reopenlist\
    +nd8322p_reopenlist+"\n"\
    +"Suggestion:\n"\
    +common_nd8322p_suggestionlist\
    +nd8322p_suggestionlist+"\n"\
    +"Best Regards,\n"\
    +tester_account.capitalize()

#   ----onvif_report---         
    onvif_report=\
    "[Final Report] "+ model_name.upper()+"-"+brand_name.upper()+"-"+ version_name + " ONVIF test --- test on " + tester_today+"\n\n"\
    "Dear David,\n"\
    "The bug status of "+ model_name.upper()+"-"+brand_name.upper()+"-"+ version_name +" ONVIF test, "+str(len(onvif_issue)+len(common_onvif_issue))+" bugs are opened and "+ str(len(onvif_suggestion)+len(common_onvif_suggestion)) +" suggestions are listed.\n"\
    "Please check it. Thanks for your great help!!\n\n"\
    "PS:\n"\
    "Full Test\n\n"\
    "TestRail link:\n"\
    +testrail_link+"\n\n"\
    "The file location:\n"\
    "\\\dqa03\QMD\\設計驗證部\\06_驗證六組\\01_ONVIF\\01_ONVIF_Report\\OBM\\v15.06"+"\\" +model_name.upper()+"-"+brand_name.upper()+"\\"+version_name+"\n\n"\
    "The Project common bug link:\n"\
    +common_project_link\
    +"The Project common bug list:\n"\
    +common_onvif_buglist+"\n"\
    +model_name.upper()+" bug link:\n"\
    +"http://dqa02/projects/"+project_id+"/issues?set_filter=1&tracker_id=69\n\n"\
    +model_name.upper()+" bug list:\n"\
    +onvif_buglist+"\n"\
    +"Reopen bug:\n"\
    +common_onvif_reopenlist\
    +onvif_reopenlist+"\n"\
    +"Suggestion:\n"\
    +common_onvif_suggestionlist\
    +onvif_suggestionlist+"\n"\
    +"Best Regards,\n"\
    +tester_account.capitalize()

#   ----shpherd_report---           
    shpherd_report=\
    "[Final Report] "+ model_name.upper()+"-"+brand_name.upper()+"-"+ version_name + " Shepherd test --- test on " + tester_today+"\n\n"\
    "Dear David,\n"\
    "The bug status of "+ model_name.upper()+"-"+brand_name.upper()+"-"+ version_name +" Shepherd test, "+str(len(shpherd_issue)+len(common_shpherd_issue))+" bugs are opened and "+ str(len(shpherd_suggestion)+len(common_shpherd_suggestion)) +" suggestions are listed.\n"\
    "Please check it. Thanks for your great help!!\n\n"\
    "PS:\n"\
    "Full Test\n\n"\
    "TestRail link:\n"\
    +testrail_link+"\n\n"\
    "The file location:\n"\
    "N/A\n\n"\
    "The Project common bug link:\n"\
    +common_project_link\
    +"The Project common bug list:\n"\
    +common_shpherd_buglist+"\n"\
    +model_name.upper()+" bug link:\n"\
    +"http://dqa02/projects/"+project_id+"/issues?set_filter=1&tracker_id=69\n\n"\
    +model_name.upper()+" bug list:\n"\
    +shpherd_buglist+"\n"\
    +"Reopen bug:\n"\
    +common_shpherd_reopenlist\
    +shpherd_reopenlist+"\n"\
    +"Suggestion:\n"\
    +common_shpherd_suggestionlist\
    +shpherd_suggestionlist+"\n"\
    +"Best Regards,\n"\
    +tester_account.capitalize()

#   ----vast_report---         
    vast_report=\
    "[Final Report] "+ model_name.upper()+"-"+brand_name.upper()+"-"+ version_name + " VAST Center test --- test on " + tester_today+"\n\n"\
    "Dear David,\n"\
    "The bug status of "+ model_name.upper()+"-"+brand_name.upper()+"-"+ version_name +" VAST test, "+str(len(vast_issue)+len(common_vast_issue))+" bugs are opened and "+ str(len(vast_suggestion)+len(common_vast_suggestion)) +" suggestions are listed.\n"\
    "Please check it. Thanks for your great help!!\n\n"\
    "PS:\n"\
    "Full Test\n\n"\
    "TestRail link:\n"\
    +testrail_link+"\n\n"\
    "The file location:\n"\
    "N/A\n\n"\
    "The Project common bug link:\n"\
    +common_project_link\
    +"The Project common bug list:\n"\
    +common_vast_buglist+"\n"\
    +model_name.upper()+" bug link:\n"\
    +"http://dqa02/projects/"+project_id+"/issues?set_filter=1&tracker_id=69\n\n"\
    +model_name.upper()+" bug list:\n"\
    +vast_buglist+"\n"\
    +"Reopen bug:\n"\
    +common_vast_reopenlist\
    +vast_reopenlist+"\n"\
    +"Suggestion:\n"\
    +common_vast_suggestionlist\
    +vast_suggestionlist+"\n"\
    +"Best Regards,\n"\
    +tester_account.capitalize()
    
    while test_type is ():
        self.m_statusBar.SetStatusText( 'Please select Test Type.' )
        break
    else:
        for item in test_type:
            if item == "All":
                self.omnicast_textCtrl.AppendText(str(omnicast_report.decode('utf-8').encode('cp950')))
                self.security_textCtrl.AppendText(str(security_report.decode('utf-8').encode('cp950')))
                self.milestone_textCtrl.AppendText(str(milestone_report.decode('utf-8').encode('cp950')))
                self.nd8321_textCtrl.AppendText(str(nd8321_report.decode('utf-8').encode('cp950')))    
                self.nd8322p_textCtrl.AppendText(str(nd8322p_report.decode('utf-8').encode('cp950')))
                self.onvif_textCtrl.AppendText(str(onvif_report.decode('utf-8').encode('cp950')))    
                self.shpherd_textCtrl.AppendText(str(shpherd_report.decode('utf-8').encode('cp950')))
                self.vast_textCtrl.AppendText(str(vast_report.decode('utf-8').encode('cp950')))
                break
            if not item =="All":
                if item == "Genetec-Omnicast":
                    self.omnicast_textCtrl.AppendText(str(omnicast_report.decode('utf-8').encode('cp950')))
                if item == "Genetec-Security center":
                    self.security_textCtrl.AppendText(str(security_report.decode('utf-8').encode('cp950')))                            
                if item == "Milestone":
                    self.milestone_textCtrl.AppendText(str(milestone_report.decode('utf-8').encode('cp950')))  
                if item == "ND8321":
                    self.nd8321_textCtrl.AppendText(str(nd8321_report.decode('utf-8').encode('cp950'))) 
                if item == "ND8322P":
                    self.nd8322p_textCtrl.AppendText(str(nd8322p_report.decode('utf-8').encode('cp950')))
                if item == "ONVIF":
                    self.onvif_textCtrl.AppendText(str(onvif_report.decode('utf-8').encode('cp950')))
                if item == "Shepherd":
                    self.shpherd_textCtrl.AppendText(str(shpherd_report.decode('utf-8').encode('cp950')))
                if item == "VAST":
                    self.vast_textCtrl.AppendText(str(vast_report.decode('utf-8').encode('cp950')))
                             
        self.m_statusBar.SetStatusText( 'Create Report successfully!' )   
    
#def updatebutton
  def updatebutton(self, event):
    self.m_statusBar.SetStatusText( 'Please wait a minute...' )
    tester_account = self.account_textCtrl.GetValue()
    tester_password = self.password_textCtrl.GetValue()
    model_name = self.model_textCtrl.GetValue()
    brand_name = self.brand_textCtrl.GetValue()
    version_name = self.version_textCtrl.GetValue()
    testrail = self.testrail_textCtrl.GetValue()
    redmine = Redmine("http://dqa02/redmine/", username=tester_account, password=tester_password)
    cct_request_issue = redmine.issue.filter(project_id='dqa-test-1-request-integration')
    model_name = model_name.upper()+"-"+brand_name.upper()+"-"+ version_name
    project_id = self.project_textCtrl.GetValue()
    common_project_id = self.common_textCtrl.GetValue()
    project_link = "http://dqa02/projects/"+project_id+"/issues?set_filter=1&tracker_id=69"
    common_project_link = "http://dqa02/projects/"+common_project_id+"/issues?set_filter=1&tracker_id=69"
    update_project_link = "<a href='"+project_link+"'>"+project_link+"</a>"
    update_common_project_link = "<a href='"+common_project_link+"'>"+common_project_link+"</a>"
    update_testrail = "<a href='"+testrail+"'>"+testrail+"</a>"
#   cct_request_issue = redmine.issue.filter(project_id='dqa-test-1-request-integration')

#   update Genetec-Omnicast
    if self.omnicast_textCtrl.IsModified() is True:
        omnicast_report = self.omnicast_textCtrl.GetValue()
        update_omnicast_report = ''
        update_omnicast_report = omnicast_report.replace(project_link, update_project_link)
        if self.common_textCtrl.IsModified() is True:
            update_omnicast_report = update_omnicast_report.replace(common_project_link, update_common_project_link)
        if self.testrail_textCtrl.IsModified() is True:
            update_omnicast_report = update_omnicast_report.replace(testrail, update_testrail)
        update_omnicast_report = update_omnicast_report.replace("\n","<br>")
       
        for issue in cct_request_issue:
            if model_name in issue.subject and "Genetec-Omnicast" in issue.subject:
                issue.custom_fields = [{'id': 80, 'value': 'Final Report'}]
                issue.notes = update_omnicast_report
                issue.save()  
                
#   update Genetec-Security-Center
    if self.security_textCtrl.IsModified() is True:
        security_report = self.security_textCtrl.GetValue()
        update_security_report = ''
        update_security_report = security_report.replace(project_link, update_project_link)
        if self.common_textCtrl.IsModified() is True:
            update_security_report = update_security_report.replace(common_project_link, update_common_project_link)
        if self.testrail_textCtrl.IsModified() is True:
            update_security_report = update_security_report.replace(testrail, update_testrail)
        update_security_report = update_security_report.replace("\n","<br>")
       
        for issue in cct_request_issue:
            if model_name in issue.subject and "Genetec-Security center" in issue.subject:
                issue.custom_fields = [{'id': 80, 'value': 'Final Report'}]
                issue.notes = update_security_report
                issue.save()     

#   update Milestone
    if self.milestone_textCtrl.IsModified() is True:
        milestone_report = self.milestone_textCtrl.GetValue()
        update_milestone_report = ''
        update_milestone_report = milestone_report.replace(project_link, update_project_link)
        if self.common_textCtrl.IsModified() is True:
            update_milestone_report = update_milestone_report.replace(common_project_link, update_common_project_link)
        if self.testrail_textCtrl.IsModified() is True:
            update_milestone_report = update_milestone_report.replace(testrail, update_testrail)
        update_milestone_report = update_milestone_report.replace("\n","<br>")
       
        for issue in cct_request_issue:
            if model_name in issue.subject and "Milestone" in issue.subject:
                issue.custom_fields = [{'id': 80, 'value': 'Final Report'}]
                issue.notes = update_milestone_report
                issue.save()    
                    
#   update ND8321
    if self.nd8321_textCtrl.IsModified() is True:
        nd8321_report = self.nd8321_textCtrl.GetValue()
        update_nd8321_report = ''
        update_nd8321_report = nd8321_report.replace(project_link, update_project_link)
        if self.common_textCtrl.IsModified() is True:
            update_nd8321_report = update_nd8321_report.replace(common_project_link, update_common_project_link)
        if self.testrail_textCtrl.IsModified() is True:
            update_nd8321_report = update_nd8321_report.replace(testrail, update_testrail)
        update_nd8321_report = update_nd8321_report.replace("\n","<br>")
       
        for issue in cct_request_issue:
            if model_name in issue.subject and "ND8321" in issue.subject:
                issue.custom_fields = [{'id': 80, 'value': 'Final Report'}]
                issue.notes = update_nd8321_report
                issue.save()   

#   update ND8322p
    if self.nd8322p_textCtrl.IsModified() is True:
        nd8322p_report = self.nd8322p_textCtrl.GetValue()
        update_nd8322p_report = ''
        update_nd8322p_report = nd8322p_report.replace(project_link, update_project_link)
        if self.common_textCtrl.IsModified() is True:
            update_nd8322p_report = update_nd8322p_report.replace(common_project_link, update_common_project_link)
        if self.testrail_textCtrl.IsModified() is True:
            update_nd8322p_report = update_nd8322p_report.replace(testrail, update_testrail)
        update_nd8322p_report = update_nd8322p_report.replace("\n","<br>")
       
        for issue in cct_request_issue:
            if model_name in issue.subject and "ND8322P" in issue.subject:
                issue.custom_fields = [{'id': 80, 'value': 'Final Report'}]
                issue.notes = update_nd8322p_report
                issue.save()  

#   update Shpherd
    if self.shpherd_textCtrl.IsModified() is True:
        shpherd_report = self.shpherd_textCtrl.GetValue()
        update_shpherd_report = ''
        update_shpherd_report = shpherd_report.replace(project_link, update_project_link)
        if self.common_textCtrl.IsModified() is True:
            update_shpherd_report = update_shpherd_report.replace(common_project_link, update_common_project_link)
        if self.testrail_textCtrl.IsModified() is True:
            update_shpherd_report = update_shpherd_report.replace(testrail, update_testrail)
        update_shpherd_report = update_shpherd_report.replace("\n","<br>")
       
        for issue in cct_request_issue:
            if model_name in issue.subject and "Shepherd" in issue.subject:
                issue.custom_fields = [{'id': 80, 'value': 'Final Report'}]
                issue.notes = update_shpherd_report
                issue.save()
                
#   update VAST
    if self.vast_textCtrl.IsModified() is True:
        vast_report = self.vast_textCtrl.GetValue()
        update_vast_report = ''
        update_vast_report = vast_report.replace(project_link, update_project_link)
        if self.common_textCtrl.IsModified() is True:
            update_vast_report = update_vast_report.replace(common_project_link, update_common_project_link)
        if self.testrail_textCtrl.IsModified() is True:
            update_vast_report = update_vast_report.replace(testrail, update_testrail)
        update_vast_report = update_vast_report.replace("\n","<br>")
       
        for issue in cct_request_issue:
            if model_name in issue.subject and "VAST" in issue.subject:
                issue.custom_fields = [{'id': 80, 'value': 'Final Report'}]
                issue.notes = update_vast_report
                issue.save()

#   update ONVIF
    if self.onvif_textCtrl.IsModified() is True:
        onvif_report = self.onvif_textCtrl.GetValue()
        update_onvif_report = ''
        update_onvif_report = onvif_report.replace(project_link, update_project_link)
        if self.common_textCtrl.IsModified() is True:
            update_onvif_report = update_onvif_report.replace(common_project_link, update_common_project_link)
        if self.testrail_textCtrl.IsModified() is True:
            update_onvif_report = update_onvif_report.replace(testrail, update_testrail)
        update_onvif_report = update_onvif_report.replace("\n","<br>")
       
        for issue in cct_request_issue:
            if model_name in issue.subject and "ONVIF" in issue.subject:
                issue.custom_fields = [{'id': 80, 'value': 'Final Report'}]
                issue.notes = update_onvif_report
                issue.save()                 
                           
    self.m_statusBar.SetStatusText( 'Update Report successfully!' )
